### ISSUE TITLE
Roadmap for 1.0 version

### ISSUE THREAD

**Issue by sgflt** [ta4j/ta4j#1208]
Could we create develop-1.0 branch as destination for partial pull requests? Some of them may not function properly without others, but pull request as all in one is unverifiable.

1. [ ] https://github.com/ta4j/ta4j/issues/1198
2. [ ] https://github.com/ta4j/ta4j/issues/1207
3. [ ] https://github.com/ta4j/ta4j/issues/1186
4. [ ] https://github.com/ta4j/ta4j/pull/1206
5. [ ] https://github.com/ta4j/ta4j/pull/1205
6. [ ] https://github.com/ta4j/ta4j/pull/1204
7. [ ] https://github.com/ta4j/ta4j/pull/1202
8. [ ] https://github.com/ta4j/ta4j/pull/1201
9. [ ] https://github.com/ta4j/ta4j/pull/1195
10. [ ] https://github.com/ta4j/ta4j/pull/1193
11. [ ] Introduce observable IndicatorContext. This modification enables possibility to propagate state of indicators into prometheus, timescaledb or other tool.
12. [ ] Drop all indicator meta layers. Numeric idnicators extends from NumericIndicator. BooleanIndicators extends from BooleanIndicator.
13. [ ] Drop indexing in APIs, indicators are treated like discrete simulation. advance() method for backtesting
14. [ ] Previous task opens possibility for streaming algorithms, which reduces complexity and need for caching
15. [ ] Introduce LiveTrading classes
16. [ ] https://github.com/ta4j/ta4j/issues/1141

**Comment by TheCookieLab** [comment]
No, we are not introducing any more integration branches. There can be an argument to eliminate the develop branch, but going the other way is the last thing we want to do.

Feature branches should be specific and focused, addressing a single bug/issue/feature at an atomic level as possible. They should also **not** depend on _other_ unmerged feature branches. A destination for partial pull requests enables many of these unwanted behaviors, which may be fine for a single developer environment but the exact opposite of best practice in a shared codebase.

I will produce a project road-map in the coming days. It will be at a high, conceptual level however will draw heavily from my private Ta4j fork (long since diverged) and (profitable) client application.

**Comment by TheCookieLab** [comment]
Your efforts here to order and organize are appreciated and not necessarily
incompatible. My road-map will be at a higher, conceptual level, which can
be subdivided into actionable tasks like what you've done here.
